export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: 'Winners Chapel International Limerick',
      description: 'Winners Chapel International Limerick is a vibrant community dedicated to spiritual growth and fellowship. Join us for services, events, and resources that inspire and uplift.',
      ogImage: '/Screenshot 2025-07-12 112109.png',
      ogImageComponent: 'ShadcnDocs',
      ogImageColor: 'light',
      umami: {
        enable: false,
        src: 'https://cloud.umami.is/script.js',
        dataWebsiteId: 'd793fbf3-461e-4e26-9ec9-4e9141df96ee',
      },
    },
    theme: {
      customizable: false,
      color: 'rose',
      colorMode: 'light',
      // colorMode: 'dark', // Uncomment to enable dark mode by default
      radius: 0.5,
    },
    banner: {
      enable: false,
      showClose: false,
      content: 'Recent Men\'s Hangout in [Pictures](/event/mens-hangout)',
      border: true,
    },
    header: {
      title: 'WCI Limerick',
      showTitle: true,
      logo: {
        light: '/Winners-Logo.png',
        dark: '/Winners-Logo.png',
      },
      darkModeToggle: false,
      languageSwitcher: {
        enable: false,
        triggerType: 'icon',
        dropdownType: 'select',
      },
      nav: [{
        title: 'About',
        to: '/about',
        target: '_self',
        showLinkIcon: false,
        description: 'Learn more about us',
        icon: 'lucide:info',
      }, {
        title: 'WSF (House Fellowship)',
        to: '/wsf',
        target: '_self',
        showLinkIcon: false,
        description: 'Learn about our WSF (House Fellowship)',
        icon: 'lucide:users',
      }, {
        title: 'Testimonies',
        to: '/testimony',
        target: '_self',
        showLinkIcon: false,
        description: 'Share your testimonies',
        icon: 'lucide:speech',
      }, {
        title: 'Events',
        to: '/event/home',
        target: '_self',
        showLinkIcon: false,
        description: 'Stay updated with our latest events',
        icon: 'lucide:calendar',
      }, {
        title: 'Giving',
        to: '/giving',
        target: '_self',
        showLinkIcon: false,
        description: 'Support our mission',
        icon: 'lucide:heart',
      }, {
        title: 'Books & Resources',
        to: '/books',
        target: '_self',
        showLinkIcon: false,
        description: 'Explore our books and resources',
        icon: 'lucide:book-open',
      }, {
        title: 'Service Units',
        to: '/service-units',
        target: '_self',
        showLinkIcon: false,
        description: 'Learn about our service units',
        icon: 'lucide:users',
      }],
    links: {
      home: {
        title: 'Instagram',
        to: 'https://www.instagram.com/winnerschapel_limerick/',
        target: '_blank',
        icon: 'skill-icons:instagram',
      },
      docs: {
        title: 'Facebook',
        to: '/',
        target: '_blank',
        icon: 'logos:whatsapp-icon',
      },
      contact: {
        title: 'Contact Us',
        to: '/',
        target: '_blank',
        icon: 'devicon:facebook',
          showLinkIcon: false,
        },
        about: {
          title: 'About Us',
          to: '/',
          target: '_blank',
          icon: 'devicon:info',
        }
      }
    },
    aside: {
      useLevel: true,
      collapse: true,
      collapseLevel: 1,
      folderStyle: 'default',
    },
    main: {
      breadCrumb: false,
      showTitle: true,
      codeCopyToast: true,
      codeCopyIcon: 'lucide:clipboard',
      editLink: {
        enable: false,
        pattern: 'https://github.com/ZTL-UwU/shadcn-docs-nuxt/edit/main/www/content/:path',
        text: 'Edit this page',
        icon: 'lucide:square-pen',
        placement: ['docsFooter'],
      },
      backToTop: true,
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'css': 'vscode-icons:file-type-css',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-light-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'lucide:terminal',
      },
    },
    footer: {
      credits: 'Website Designed and Developed by WCI-Limerick Media/Technical Service Unit © 2025',
    },
    toc: {
      enable: true,
      enableInMobile: false,
      enableInHomepage: false,
      title: 'On this page',
      links: [
        {
          title: 'Shiloh 2025',
          icon: 'emojione:church',
          showLinkIcon: true,
        },
        {
          title: 'The Ark Legacy Project',
          icon: 'noto-v1:stadium',
          to: 'https://davidoyedepo.org/theark',
          target: '_blank',
          showLinkIcon: true,
        },
      ],
      iconLinks: [
        
      ],
      carbonAds: {
        enable: false,
        disableInDev: true,
        disableInMobile: true,
        fallback: false,
        fallbackMessage: 'Please support us by disabling your ad blocker.',
        code: 'CW7ITKJN',
        placement: 'shadcn-docs-nuxtvercelapp',
        format: 'cover',
      },
    },
    search: {
      enable: false,
      inAside: false,
      style: 'input',
    },
    data: {},
  },
});