export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: 'Knowledge Centre',
      description: 'ESW Knowledge Centre',
      ogImage: '/Screenshot 2025-07-04 144755.png',
      ogImageComponent: 'ShadcnDocs',
      ogImageColor: 'light',
      umami: {
        enable: false,
        src: 'https://cloud.umami.is/script.js',
        dataWebsiteId: 'd793fbf3-461e-4e26-9ec9-4e9141df96ee',
      },
    },
    theme: {
      customizable: false,
      color: 'rose',
      colorMode: 'light',
      // colorMode: 'dark', // Uncomment to enable dark mode by default
      radius: 0.5,
    },
    banner: {
      enable: false,
      showClose: true,
      content: 'Welcome to **shadcn-docs-nuxt**',
      to: 'https://github.com/ZTL-UwU/shadcn-docs-nuxt',
      target: '_blank',
      border: true,
    },
    header: {
      title: 'Knowledge Centre',
      showTitle: true,
      logo: {
        light: '/logo.svg',
        dark: '/ESW-Logo-Light.svg',
      },
      darkModeToggle: false,
      languageSwitcher: {
        enable: false,
        triggerType: 'icon',
        dropdownType: 'select',
      },
      nav: [{
        title: 'About',
        to: '/',
        target: '_self',
        showLinkIcon: false,
        description: 'Learn more about us',
        icon: 'lucide:info',
      }, {
        title: 'WSF (House Fellowship)',
        to: '/docs',
        target: '_self',
        showLinkIcon: false,
        description: 'Learn about our WSF (House Fellowship) program',
        icon: 'lucide:users',
      }, {
        title: 'Events',
        to: 'https://eswapis.vercel.app',
        target: '_blank',
        showLinkIcon: true,
        description: 'Stay updated with our latest events',
        icon: 'lucide:calendar',
      }, {
        title: 'Giving',
        to: '/help-centre',
        target: '_self',
        showLinkIcon: false,
        description: 'Support our mission',
        icon: 'lucide:heart',
      }, {
        title: 'Bookstore & Resources',
        to: '/contact',
        target: '_self',
        showLinkIcon: false,
        description: 'Explore our bookstore and resources',
        icon: 'lucide:book-open',
      }, {
        title: 'Service Units',
        links: [
          {
            icon: 'lucide:users',
            title: 'Altar Ministers',
            to: 'mailto:info@esw.com',
            target: '_self',
          },
          {
            icon: 'lucide:music',
            title: 'Choir',
            to: 'tel:+1234567890',
            target: '_self',
          },
          {
            icon: 'lucide:camera',
            title: 'Sanctuary Keepers',
            to: 'https://eswapis.vercel.app',
            target: '_blank',
          },
          {
            icon: 'lucide:shield',
            title: 'Ushering',
            to: '/docs',
            target: '_self',
          },
          {
            icon: 'lucide:video',
            title: 'Media',
            to: '/docs',
            target: '_self',
          },
          {
            icon: 'lucide:book',
            title: 'Children’s Church',
            to: '/docs',
            target: '_self',
          },
        ],
      }],
    },
    aside: {
      useLevel: true,
      collapse: true,
      collapseLevel: 1,
      folderStyle: 'default',
    },
    main: {
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: true,
      codeCopyIcon: 'lucide:clipboard',
      editLink: {
        enable: false,
        pattern: 'https://github.com/ZTL-UwU/shadcn-docs-nuxt/edit/main/www/content/:path',
        text: 'Edit this page',
        icon: 'lucide:square-pen',
        placement: ['docsFooter'],
      },
      backToTop: true,
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'css': 'vscode-icons:file-type-css',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-light-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'lucide:terminal',
      },
    },
    footer: {
      credits: '2025 © Winners Chapel Limerick',
      links: [
        {
          icon: 'lucide:users',
          title: 'About us ',
          to: 'https://esw.com/about-us/',
          target: '_blank',
        },
        {
          icon: 'lucide:package-open',
          title: 'Products & Services',
          to: 'https://esw.com/product-and-services/',
          target: '_blank',
        },
        {
          icon: 'lucide:factory',
          title: 'Industry expertise',
          to: 'https://esw.com/industry-expertise/',
          target: '_blank',
        },
        {
          icon: 'lucide:arrow-right-from-line',
          title: 'Talk to an expert',
          to: 'https://esw.com/talk-to-an-expert/',
          target: '_blank',
        },
        {
          icon: 'lucide:headset',
          title: 'Customer service',
          to: 'https://service.esw.com/',
          target: '_blank',
        },
        {
          icon: 'lucide:file-lock',
          title: 'Trust Centre',
          to: 'https://trust.esw.com/',
          target: '_blank',
        },
        {
          icon: 'lucide:globe-lock',
          title: 'Privacy Policy',
          to: 'https://esw.com/privacy-policy/',
          target: '_blank',
        },
      ],
    },
    toc: {
      enable: true,
      enableInMobile: false,
      enableInHomepage: false,
      title: 'On this page',
      links: [
        {
          title: 'Login',
          icon: 'lucide:log-in',
          showLinkIcon: true,
        },
        {
          title: 'API Reference',
          icon: 'lucide:file-json',
          to: 'https://eswapis.vercel.app/',
          target: '_blank',
          showLinkIcon: true,
        },
      ],
      iconLinks: [
        
      ],
      carbonAds: {
        enable: false,
        disableInDev: true,
        disableInMobile: true,
        fallback: false,
        fallbackMessage: 'Please support us by disabling your ad blocker.',
        code: 'CW7ITKJN',
        placement: 'shadcn-docs-nuxtvercelapp',
        format: 'cover',
      },
    },
    search: {
      enable: true,
      inAside: false,
      style: 'input',
    },
    data: {},
  },
});